<?php

########################################################################
# Extension Manager/Repository config file for ext: "bitform"
#
# Auto generated by Extension Builder 2018-03-19
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = [
    'title' => 'Lufed IT Template',
    'description' => '',
    'category' => 'misc',
    'version' => '1.0.0',
    'state' => 'alpha',
    'uploadfolder' => false,
    'createDirs' => '',
    'clearcacheonload' => false,
    'author' => 'Artem Olenchenko',
    'author_email' => 'a.olenchenko@lufed-it.de',
    'author_company' => 'Lufed IT',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-9.5.8',
            'vhs' => '4.4.0-0.0.0',
            'flux' => '8.2.1',
            //'fluidcontent' => '5.2.0',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];

